CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "description" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" integer NOT NULL,
  "full_name" varchar(150) NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "phone" varchar(20) NOT NULL,
  "profile_photo" varchar(255),
  "resume" varchar(255) NOT NULL,
  "bio" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "slug" varchar(120) UNIQUE NOT NULL,
  "icon" varchar(255),
  "description" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "organizations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) UNIQUE NOT NULL,
  "logo" varchar(255),
  "website" varchar(255),
  "description" text,
  "location" varchar(150),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "opportunities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" integer NOT NULL,
  "organization_id" integer NOT NULL,
  "created_by" integer NOT NULL,
  "title" varchar(255) NOT NULL,
  "slug" varchar(255) UNIQUE NOT NULL,
  "description" text,
  "requirements" text,
  "benefits" text,
  "location" varchar(150),
  "deadline" date,
  "source_url" varchar(255),
  "published_at" timestamp,
  "status" varchar(30) NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "bookmarks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "opportunity_id" integer NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "applications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "opportunity_id" integer NOT NULL,
  "status" varchar(30) NOT NULL,
  "applied_at" timestamp NOT NULL,
  "updated_at" timestamp
);

CREATE TABLE "notifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "title" varchar(255) NOT NULL,
  "message" text NOT NULL,
  "type" varchar(30) NOT NULL,
  "is_read" boolean NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "notification_preferences" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "email_enabled" boolean NOT NULL,
  "system_enabled" boolean NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE UNIQUE INDEX ON "bookmarks" ("user_id", "opportunity_id");

CREATE UNIQUE INDEX ON "applications" ("user_id", "opportunity_id");

CREATE UNIQUE INDEX ON "notification_preferences" ("user_id");

COMMENT ON COLUMN "opportunities"."status" IS 'Draft | Published | Archived';

COMMENT ON COLUMN "applications"."status" IS 'Pending | Reviewed | Accepted | Rejected | Withdrawn';

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "opportunities" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "opportunities" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "opportunities" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bookmarks" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bookmarks" ADD FOREIGN KEY ("opportunity_id") REFERENCES "opportunities" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "applications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "applications" ADD FOREIGN KEY ("opportunity_id") REFERENCES "opportunities" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notification_preferences" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
